# Generated by Django 4.0.2 on 2022-02-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MC_Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_header', models.CharField(max_length=20)),
                ('card_image', models.ImageField(upload_to='mc_images/%Y/%m/%d')),
                ('card_body', models.TextField()),
                ('card_footer', models.CharField(max_length=20)),
            ],
        ),
    ]
