# Generated by Django 4.0.2 on 2022-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_view', '0002_mc_dilikates_alter_mc_coffee_card_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_header', models.CharField(max_length=20, verbose_name='Наименование карты')),
                ('card_image', models.ImageField(upload_to='mc_images/%Y/%m/%d', verbose_name='Изображение карты')),
                ('card_body', models.TextField(verbose_name='Текст карты')),
                ('card_footer', models.CharField(max_length=20, verbose_name='Футер Карты')),
            ],
        ),
    ]
