# Generated by Django 4.0.2 on 2022-02-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_view', '0003_mc_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категорий кофе')),
            ],
        ),
        migrations.AddField(
            model_name='mc_coffee',
            name='category_coffee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mc_view.category_coffee'),
        ),
    ]
