# Generated by Django 4.0.2 on 2022-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_view', '0004_category_coffee_mc_coffee_category_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Dilikates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категорий диликатесов')),
            ],
        ),
    ]
