# Generated by Django 4.0.2 on 2022-02-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_view', '0005_category_dilikates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_dilikates',
            name='category_dilikates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mc_view.category_dilikates'),
        ),
    ]
