# Generated by Django 4.0.2 on 2022-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_view', '0006_mc_dilikates_category_dilikates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
                ('avatar_user', models.ImageField(upload_to='mc_images/%Y/%m/%d/', verbose_name='Аватар пользователя')),
            ],
        ),
        migrations.DeleteModel(
            name='MC_Drinks',
        ),
    ]
