# Generated by Django 4.0.2 on 2022-02-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_view', '0007_profile_delete_mc_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Make_Profile',
        ),
    ]
